// <auto-generated />
using FerragensOnline.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FerragensOnline.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200606155419_estoque")]
    partial class estoque
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FerragensOnline.Models.Estoque", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Classe")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Codigo_Barras")
                        .HasColumnType("int");

                    b.Property<string>("Fornecedor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Preco_Custo")
                        .HasColumnType("int");

                    b.Property<int>("Preco_Final")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Estoques");
                });
#pragma warning restore 612, 618
        }
    }
}
